config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'static_pages#top'
  get 'static_pages/index' , to:  'static_pages#index'
  get 'static_pages/help',  to: 'static_pages#help'
  get 'static_pages/about',  to: 'static_pages#about'
  resources :comments do
    resources :opinions, only:[ :edit, :update, :create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :opinions, dependent: :destroy

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :comment
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.includes(:opinions).find(params[:id])
    @opinion = Opinion.new
    @opinions = Opinion.find_by(comment_id: params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to "/"
    else
      redirect_to "new"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to static_pages_index_path
    else
      redirect_to "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to static_pages_index_path
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :title, :song, :singer, :story)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  def create
    @comment = Comment.find(params[:comment_id])
    @opinion = Opinion.new(params_opinion)
    @opinion.comment = @comment

    if @opinion.save
      redirect_to comment_path(@comment)
    else
      render "comments/show"
    end
  end

  def edit
    @opinion = Opinion.find(params[:id])
  end

  def update
    @opinion = Opinion.find(params[:id])

    if @opinion.update_attributes(params_opinion)
      redirect_to static_pages_index_path
    else
      redirect_to "edit"
    end
  end

  def destroy
    @opinion = Opinion.find(params[:id])
    @opinion.destroy
    redirect_to static_pages_index_path
  end

  private

  def params_opinion
    params.require(:opinion).permit(:comment_id, :name, :content, :image, :remove_image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end

  def index
    @comments = Comment.all.search(params[:search]).paginate(page: params[:page], per_page: 30).order('created_at desc')
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = "思い出ソング"
    if title.empty?
      base_title
    else
      "#{title}/#{base_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_opinions.html.erb
<div class="list-group">
<% @comment.opinions.each_with_index do |opinion,i| %>
  <div class="list-group-item" >
    <div class="d-flex w-100 justify-content-between">
      <a class="mb-1" href=<%=edit_comment_opinion_path(@comment,opinion)%> >
        <%= i+1 %>:<%= opinion.name %></a>
      <small><%= opinion.created_at %></small>
    </div>
    <p class="mb-1"><%= opinion.content %></p>
    <p class="mb-1"><%=image_tag opinion.image.url if opinion.image? %></p>
  </div>
<% end %>
</div>

<div class="card">
  <div class="card-body">
    <h4 class="card-title">コメントしてみよう</h4>
      <%= form_for @opinion, url: comment_opinions_path(@comment, @opinion) do |f| %>
        <div class="form-group">
          <%= f.label :名前 %>
          <%= f.text_field :name,placeholder:"名無しマン", class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :コメント %>
          <%= f.text_area :content,placeholder:"ええやんけ、、",class:'form-control' %>
        </div>
        <div class="form-group">
          <%=f.label "画像をアップロード" %>
          <%= f.file_field :image, class:'form-control' %>
        </div>
          <%= f.submit value="コメントする", class: "btn btn-large btn-primary" %>
      <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<% provide :title, '編集' %>

    <%= form_for(@comment) do |f| %>
      <div class="form-group">
        <%= f.label :タイトル %>
        <%= f.text_field :title, class:'form-control'%>

        <%= f.label :曲名 %>
        <%= f.text_field :song, class:'form-control' %>

        <%= f.label :歌手 %>
        <%= f.text_field :singer, class:'form-control' %>

        <%= f.label :思い出 %>
        <%= f.text_area :story, class:'form-control' %>

        <%= f.label :いつ %>
        <%= f.text_field :when, class:'form-control' %>

        <%= f.submit value="編集する", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
<%= button_to "削除する", comment_path(@comment),method: :delete, data: {confirm: "本当に削除しますか？"} %>
<%= button_to "戻る", static_pages_index_path, method: :get %>

app/views/comments/new.html.erb
<% provide :title, '新規作成' %>

<%= form_for(@comment) do |f| %>
    <%= f.label :タイトル %>
    <%= f.text_field :title,placeholder:"例）最後の一曲", class:'form-control'%>

    <%= f.label :曲名 %>
    <%= f.text_field :song,placeholder:"例）永遠の嘘をついてくれ",  class:'form-control' %>

    <%= f.label :歌手 %>
    <%= f.text_field :singer,placeholder:"例）中島みゆき",  class:'form-control' %>

    <%= f.label :思い出 %>
    <%= f.text_area :story,placeholder:"例）彼女と最後に会う日でした。",  class:'form-control' %>

    <%= f.label :いつ %>
    <%= f.text_field :when,placeholder:"例）高校３年生",  class:'form-control' %>

  <%= f.submit value= "投稿する", class: "btn btn-large btn-primary" %>
<% end %>

app/views/comments/show.html.erb
<% provide :title, @comment.title %>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <a class="display-3" href=<%= edit_comment_path(@comment) %>>
      <%= @comment.title %></a>
        <p>あれは<%= @comment.when %>の時でした、、</p>
        <p class="lead"><%= @comment.story %></p>
        <p>それでは聞いてください。</p>
      <h5><%= @comment.singer %>で<%= @comment.song %></h5>
  </div>
</div>

<%= render "comments/opinions" %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href= <%= static_pages_index_path%> >
    <img src="https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Topimage_(2ch).png/250px-Topimage_(2ch).png" width="30" height="30" class="d-inline-block align-top" alt="">
    思い出そんぐ
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href= <%= static_pages_index_path%>>トップに戻る<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= <%= new_comment_path%>>新しい思い出を書く</a>
      </li>
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           その他
         </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href=<%=static_pages_about_path %>>このサイトについて</a>
           <a class="dropdown-item" href=<%= static_pages_help_path %>>困ったら！</a>
         </div>
       </li>
    </ul>
    <%= form_tag(static_pages_index_path,:method => 'get') do %>
    <%= text_field_tag :search,'', placeholder:"思い出そんぐを探す"  %>
    <%= submit_tag 'Search' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title><%= page_title(yield(:title)) %></title>
    <link rel="shortcut icon" href="https://image.itmedia.co.jp/nl/articles/1807/22/miya_1807irasutoyafig01.jpg" type="image/vnd.microsoft.icon">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%=render "layouts/header" %>
    <%= yield %>
    <%=render "layouts/footer" %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/opinions/edit.html.erb
<% provide :title, '編集' %>

<%= form_for(@opinion,url:comment_opinion_path,method: :patch) do |f| %>
  <div class="form-group">
    <%= f.label :名前 %>
    <%= f.text_field :name,class:'form-control'%>

    <%= f.label :コメント %>
    <%= f.text_field :content, class:'form-control' %>

    <%=image_tag @opinion.image.url if @opinion.image? %>
    <%=f.label "画像を変更する" %>
    <%=f.file_field :image %>
    <%=f.label "画像を削除する" %>
    <%=f.check_box :remove_image %>

    <%= f.submit value="編集する", class: "btn btn-large btn-primary" %>

  </div>
<% end %>
<%= button_to "削除する", comment_opinion_path(@opinion),method: :delete, data: {confirm: "本当に削除しますか？"}%>
<%= button_to "戻る", comment_path(@opinion.comment_id), method: :get %>

app/views/static_pages/_comments.html.erb
<ul class="list-group">
  <% @comments.each_with_index do |comment, i| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
     <a href=<%=comment_path(comment)%>><%= i+1 %>:<%= comment.title%></a>
      <span class="badge badge-primary badge-pill"><%= comment.opinions.count %></span>
    </li>
  <% end %>
</ul>

<%= will_paginate @comments %>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>
<div class="media">
  <div class="media-body">
    <h5 class="mt-0 mb-1">思い出そんぐについて</h5>
    このサイトは、【自分の思い出をベースに曲を紹介するサイト】です。誰かの思い出とともに一曲聞いてみましょう。
  </div>
  <img class="d-flex ml-3" src="https://d2oe4hwshyef6j.cloudfront.net/production/uploads/image/post_body_picture/image/278502/picture_mobile_adc2276adce9c2bfdeeb016acf6aa81767ab28b9" alt="Generic placeholder image">
</div>

app/views/static_pages/help.html.erb
<% provide :title, 'Help' %>
<div class="media">
  <div class="media-body">
    <h5 class="mt-0 mb-1">困ったら</h5>
    自分のエピソードを書いてみよう。
  </div>
  <img class="d-flex ml-3" src="https://www.asahicom.jp/articles/images/AS20180317002915_comm.jpg" alt="Generic placeholder image">
</div>

app/views/static_pages/index.html.erb
<% provide :title, 'まとめ' %>

<%=render "comments" %>

app/views/static_pages/top.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">どうも!</h1>
    <img class="img-thumbnail" src="https://mengym.net/wp-content/uploads/2017/10/motemote-sayonara-matte.jpg" alt="サムネイル画像">
    <p class="lead">思い出の一曲をストーリーとともに教えてください。</p>
    <a class="btn btn-outline-primary btn-lg" href=<%= static_pages_index_path%> role="button">詳しく見てみよう</a>
  </div>
</div>
<div class="container">
  <h1>Made by 入村遼平</h1>
  <p>２チャンネルのクローンアプリ</p>
</div>